### ISSUE TITLE
java.lang.NoSuchMethodError: scala.runtime.ScalaRunTime$.genericWrapArray(Ljava/lang/Object;)Lscala/collection/immutable/ArraySeq

### ISSUE THREAD

**Issue by GeoffMontee** [scylladb/scylla-migrator#184]
When trying to load data from S3, the following error is seen:

```
Exception in thread "main" java.lang.NoSuchMethodError: scala.runtime.ScalaRunTime$.genericWrapArray(Ljava/lang/Object;)Lscala/collection/immutable/ArraySeq;
	at com.scylladb.migrator.BuildInfo$.<clinit>(BuildInfo.scala:10)
	at com.scylladb.migrator.Migrator$.main(Migrator.scala:25)
	at com.scylladb.migrator.Migrator.main(Migrator.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1029)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by julienrf** [comment]
This error happens when there is a mismatch in Scala version. The ScyllaDB Migrator 0.9.x series needs Scala 2.13, but you probably installed Scala 2.12. What is your Scala/Spark installation process?

**Comment by GeoffMontee** [comment]
OK, I see.

When you download Spark 3.5.1, there are multiple options to choose from. The default option is Scala 2.12. To get Scala 2.13, you have to select a special package. See here:

https://spark.apache.org/downloads.html

**Comment by julienrf** [comment]
I am closing this issue because you found the solution.
