### ISSUE TITLE
Unable to read the export manifest summary: DecodingFailure at .itemCount: Int

### ISSUE THREAD

**Issue by GeoffMontee** [scylladb/scylla-migrator#186]
A customer saw the following error when migrating from a DDB S3 export:

```
Exception in thread "main" java.lang.RuntimeException: Unable to read the export manifest summary: DecodingFailure at .itemCount: Int
	at scala.sys.package$.error(package.scala:27)
	at com.scylladb.migrator.readers.DynamoDBS3Export$.$anonfun$readRDD$1(DynamoDBS3Export.scala:69)
	at scala.util.Either.fold(Either.scala:190)
	at com.scylladb.migrator.readers.DynamoDBS3Export$.readRDD(DynamoDBS3Export.scala:69)
	at com.scylladb.migrator.alternator.AlternatorMigrator$.migrateFromS3Export(AlternatorMigrator.scala:31)
	at com.scylladb.migrator.Migrator$.main(Migrator.scala:52)
	at com.scylladb.migrator.Migrator.main(Migrator.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1029)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by GeoffMontee** [comment]
Apparently the fix is to change `itemCount` from `Int` to `Bigint` here:

https://github.com/scylladb/scylla-migrator/blob/c38f58261416008e6a11efd58b35d2608a92e594/migrator/src/main/scala/com/scylladb/migrator/readers/DynamoDBS3Export.scala#L174

**Comment by julienrf** [comment]
Indeed, using an `Int` here was too small. I switched to `Long` in #187 to match what is used in the AWS Java SDK.
